version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Logging in to AWS CodeArtifact...
      - CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 608145123434 --region us-east-1 --query authorizationToken --output text`
      - export CODEARTIFACT_AUTH_TOKEN

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -s settings.xml

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - target/nextwork-web-project.war
  discard-paths: no